version: "2"

services:
  db:
    image: 'mysql:5.6'
    environment:
      MYSQL_ROOT_PASSWORD: 152030
    volumes:
      - 'mysql-data:/var/lib/mysql'

  website:
    depends_on:
      - db
    build: .
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - '.:/usr/src/app'
volumes:
  mysql-data:
